### ISSUE TITLE
Web footer

### ISSUE THREAD

**Issue by EvaMart** [FAIRplus/WP3_FAIR_tooling#43]
What should we include in the footer? Is there any policy in FAIRplus for this?
The current one is a super minimal BSC one.
![image](https://user-images.githubusercontent.com/11412829/150139349-a3776321-2907-41ee-a56b-b7415d74c261.png)

**Comment by FuqiX** [comment]
the standard FAIRplus footer https://fairplus-project.eu/

**Comment by EvaMart** [comment]
Done
![image](https://user-images.githubusercontent.com/11412829/151557989-db1ea6a8-8d17-4103-9a9a-e91b23fdfbff.png)
